### PR TITLE
Branch tool

### PR DESCRIPTION
**Pull request by dteague**
A quick little wrapper for the branches so adding branches is less likely to cause an error by forgetting to add to both spots. Might slow things down, but could make code more readable.
Can also remove branches from .h file, but didn't want to mess with the UWVV stuff and mess it up

my editor uses 2 spaces, not 4 for c++ files, theres a lot of stupid diffs between our repos, so sry :slightly_frowning_face:

### CODE REVIEW

**Comment by kdlong** [comment]
Looks good!

My only concern is that there is one important missing feature, which is the fact that you sometimes want to only want to call GetEntry on entires in specific cases, e.g., if you have a histogram you only want to fill in certain cases:

https://github.com/kdlong/VVAnalysis/blob/master/src/WZSelector.cc#L725-L733

I'll try it out and see if I have any issue, then we can decide if we want to merge before or after implementing this feature.

**Comment by dteague** [comment]
https://gist.github.com/dteague/d3d4f453ddf7e19ee8d59bf76d880994
I'm bad with git, so here's a gist. we could just add a part for these specific branches. Def give it a go. It can at the very least make the code have less lines. not super high priority, but kinda nice. I'll be using it in the TTTselector for now

**Comment by kdlong** [comment]
Perf, I'll try it out.

But you gotta use git :) I want to keep track of who made the changes etc. We'll sort out the commit problems by skype or in person Wednesday.

**Comment by dteague** [comment]
Added the specific part. I haven't really tested it yet, but it should be the same as before, just need to do:
```b.SetSpecificBranch(<name>, <holder>);``` in the set function and 
```b.SetSpecificEntry(<entry>, <name>);``` to activate that branch

**Comment by kdlong** [comment]
Do you mind dividing this into separate pull requests? I'm trying to merge now but I've diverged with the Z selector to the point that it's probably easier to start fresh now. I would do

1) Your config and updates to .gitignore (this can be trivially merged)
2) The BranchSManager.h file (you can divide into .cc/.h if you want)
3) Changes to the ZSelector to use the BranchManager (this may need to be redone, I can also do it)

**Comment by dteague** [comment]
Closing as per request

**Pull request closed without merging**
